#!/bin/bash

# Load variables from the external file
source ./env

# Set up partitions
sgdisk -Z ${DISK}
sgdisk -n1:1M:+512M -t1:ef00 ${DISK}
sgdisk -n2:0:0 -t2:bf01 ${DISK}

# Format the EFI partition
mkfs.fat -F32 ${EFI_PARTITION}

# Set up ZFS
modprobe zfs
echo ${ENCRYPTION_PASSWORD} | zpool create -f -o ashift=12 -O encryption=on -O keyformat=passphrase -O keylocation=prompt -O acltype=posixacl -O xattr=sa -O dnodesize=auto -O normalization=formD -O mountpoint=none ${POOL_NAME} ${ZFS_PARTITION}
zfs create -o mountpoint=none ${ROOT_DATASET}
zfs create -o mountpoint=legacy ${ROOT_DATASET}/ROOT
zfs create -o mountpoint=legacy ${ROOT_DATASET}/home

# Mount the filesystems
mount -t zfs ${ROOT_DATASET}/ROOT /mnt
mkdir /mnt/home
mount -t zfs ${ROOT_DATASET}/home /mnt/home
mkdir /mnt/boot
mount ${EFI_PARTITION} /mnt/boot

# Install base system
pacstrap /mnt base linux linux-firmware zfs-utils

# Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

# Chroot into the new system
arch-chroot /mnt /bin/bash <<EOF

# Set up timezone and locale
ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
hwclock --systohc
echo "${LOCALE} UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=${LOCALE}" > /etc/locale.conf
echo "KEYMAP=${KEYMAP}" > /etc/vconsole.conf

# Set up hostname
echo "${HOSTNAME}" > /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 ${HOSTNAME}.localdomain ${HOSTNAME}" >> /etc/hosts

# Install bootloader
bootctl install
cat <<BOOTLOADER > /boot/loader/loader.conf
default arch
timeout 3
editor 0
BOOTLOADER

cat <<ARCH > /boot/loader/entries/arch.conf
title   Arch Linux
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options zfs=${ROOT_DATASET}/ROOT rw
ARCH

# Set root password
echo "root:${PASSWORD}" | chpasswd

# Create user
useradd -m -G wheel -s /bin/bash ${USERNAME}
echo "${USERNAME}:${PASSWORD}" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

# Enable ZFS services
systemctl enable zfs-import-cache
systemctl enable zfs-mount
systemctl enable zfs-import.target
systemctl enable zfs.target

EOF

# Unmount filesystems
umount -R /mnt

echo "Installation complete. Reboot into your new system."
