#!/bin/bash

# Load variables from env file
source ./env

# Set up partitions
sgdisk -o $DISK
sgdisk -n 1:0:+512M -t 1:ef00 $DISK
sgdisk -n 2:0:0 -t 2:8300 $DISK

# Format partitions
mkfs.fat -F32 ${DISK}p1
cryptsetup luksFormat ${DISK}p2
cryptsetup open ${DISK}p2 cryptroot
mkfs.btrfs /dev/mapper/cryptroot

# Mount partitions
mount /dev/mapper/cryptroot /mnt
btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@home
umount /mnt
mount -o noatime,compress=zstd,subvol=@ /dev/mapper/cryptroot /mnt
mkdir /mnt/home
mount -o noatime,compress=zstd,subvol=@home /dev/mapper/cryptroot /mnt/home
mkdir /mnt/boot
mount ${DISK}p1 /mnt/boot

# Install base system
pacstrap /mnt base linux linux-firmware btrfs-progs

# Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

# Chroot into the new system
arch-chroot /mnt /bin/bash <<EOF

# Set up timezone, locale, and hostname
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
hwclock --systohc
echo $LOCALE UTF-8 >> /etc/locale.gen
locale-gen
echo LANG=$LOCALE > /etc/locale.conf
echo KEYMAP=$KEYMAP > /etc/vconsole.conf
echo $HOSTNAME > /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1 localhost" >> /etc/hosts
echo "127.0.1.1 $HOSTNAME.localdomain $HOSTNAME" >> /etc/hosts

# Set root password
echo "root:$ROOTPASSWORD" | chpasswd

# Install necessary packages
pacman -S --noconfirm grub efibootmgr networkmanager i3 xorg xorg-xinit ttf-dejavu ttf-liberation

# Enable services
systemctl enable NetworkManager

# Configure mkinitcpio
sed -i 's/^HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/HOOKS=(base udev autodetect modconf block encrypt filesystems keyboard fsck)/' /etc/mkinitcpio.conf
mkinitcpio -P

# Install systemd-boot
bootctl install
cat <<BOOTLOADER > /boot/loader/loader.conf
default arch
timeout 3
editor 0
BOOTLOADER

cat <<ARCH > /boot/loader/entries/arch.conf
title Arch Linux
linux /vmlinuz-linux
initrd /initramfs-linux.img
options cryptdevice=UUID=$(blkid -s UUID -o value ${DISK}p2):cryptroot root=/dev/mapper/cryptroot rw
ARCH

# Create user
useradd -m -G wheel -s /bin/bash $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

EOF

# Unmount and reboot
umount -R /mnt
cryptsetup close cryptroot
